name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"
 
on:
 push:
   branches:
   - main
 pull_request:
   branches:
   - main
 
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.3.0
    
     - name: Terraform init
       id: init
       run: terraform init 
 
     - name: Terraform format
       id: fmt
       run: terraform fmt -check
    
     - name: Terraform validate
       id: validate
       run: terraform validate
 
     - name: Terraform plan
       id: plan
       if: github.event_name == 'pull_request'
       run: terraform plan -no-color -input=false
       continue-on-error: true
    
     - uses: actions/github-script@v6
       if: github.event_name == 'pull_request'
       env:
         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
       with:
         script: |
           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
           <details><summary>Show Plan</summary>
 
           \`\`\`\n
           ${process.env.PLAN}
           \`\`\`
 
           </details>
           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
           github.rest.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: output
           })
 
     - name: Terraform Plan Status
       if: steps.plan.outcome == 'failure'
       run: exit 1
 
     - name: Terraform Apply
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: terraform apply -auto-approve -input=false

     # Run Pytest
     - name: Set up Python environment
       if: github.event_name == 'push' || github.event_name == 'pull_request'
       uses: actions/setup-python@v4
       with:
         python-version: "3.11"

     - name: Install dependencies
       if: github.event_name == 'push' || github.event_name == 'pull_request'
       run: |
         cd ..
         cd Website1
         python -m pip install --upgrade pip
         pip install -r requirements.txt

     - name: Run Pytest
       if: github.event_name == 'push' || github.event_name == 'pull_request'
       run: |
         cd ..
         cd Website1
         pytest

     # Docker Build and Push
     - name: Log in to Amazon ECR
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       uses: aws-actions/amazon-ecr-login@v1

     - name: Build Docker Image
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: |
         docker build -t ${{ secrets.ECR_REPOSITORY_NAME }}:latest .
         docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

     - name: Push Docker Image to ECR
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: |
         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

     # Run Pytest
     - name: Set up Python environment
       if: github.event_name == 'push' || github.event_name == 'pull_request'
       uses: actions/setup-python@v4
       with:
         python-version: "3.11"

     - name: Install dependencies
       if: github.event_name == 'push' || github.event_name == 'pull_request'
       run: |
         cd ..
         cd Website1
         python -m pip install --upgrade pip
         pip install -r requirements.txt

     - name: Run Pytest
       if: github.event_name == 'push' || github.event_name == 'pull_request'
       run: |
         cd ..
         cd Website1
         pytest

     # Docker Build and Push
     - name: Log in to Amazon ECR
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       uses: aws-actions/amazon-ecr-login@v1
       run: |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

     - name: Build Docker Image
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: |
         docker build -t ${{ secrets.ECR_REPOSITORY_NAME }}:latest .
         docker tag ${{ secrets.ECR_REPOSITORY_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest

     - name: Push Docker Image to ECR
       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       run: |
         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPOSITORY_NAME }}:latest
